spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  #邮箱配置
  mail:
    host:
    username:
    password:
    properties.mail.smtp.port:
    from:  # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  #文件上传大小限制
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB

  #对象存储文件夹
upload:
  active: prod

  #S3配置
filestorage:
  endpoint:
  accessKey:
  secretKey:
  bucketName:

  #psp配置
psp:
  applicationId:
  applicationToken:
  url:

  #oa接口配置
oa:
  token:

  #feign配置
feign:
  client:
    file:
      path:
